#cloud-config
package_update: true
package_upgrade: true
packages:
 - nginx
 - wget
 - curl


runcmd:
 - mkdir /run/stage
 - [ curl, "https://raw.githubusercontent.com/gustavmk/hollow_aws/main/nginx/index.html", -OL, /run/stage/index.html ]
 - [ curl, "https://raw.githubusercontent.com/gustavmk/hollow_aws/main/nginx/custom_50x.html", -OL, /run/stage/custom_50x.html ]
 - [ curl, "https://raw.githubusercontent.com/gustavmk/hollow_aws/main/nginx/default.conf", -OL, /run/stage/default.conf ]
 - [ sh, mv /run/stage/default.conf /etc/nginx/conf.d/default.conf ]
 - [ sh, mv /run/stage/custom_50x.html /usr/share/nginx/html/custom_50x.html ]
 - [ sh, mv /run/stage/index.html  /usr/share/nginx/html ]

 
final_message: "The system is finally up, after $UPTIME seconds"